title: Decadence Church
markdown: kramdown
highlighter: rouge
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
excerpt_separator: <!-- more -->
